<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="4" passed="2" failed="0" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-07T09:58:52Z" name="Default suite" finished-at="2024-01-07T09:58:52Z" duration-ms="64">
    <groups>
      <group name="Smoke">
        <method signature="TestNG1.B()[pri:0, instance:Frameworks.TestNG1@5f354bcf]" name="B" class="Frameworks.TestNG1"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2024-01-07T09:58:52Z" name="Default test" finished-at="2024-01-07T09:58:52Z" duration-ms="64">
      <class name="Frameworks.TestNG1">
        <test-method signature="B()[pri:0, instance:Frameworks.TestNG1@5f354bcf]" started-at="2024-01-07T15:28:52Z" name="B" finished-at="2024-01-07T15:28:52Z" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- B -->
        <test-method signature="Demo(java.lang.String)[pri:0, instance:Frameworks.TestNG1@5f354bcf]" started-at="2024-01-07T15:28:52Z" name="Demo" finished-at="2024-01-07T15:28:52Z" duration-ms="0" status="SKIP">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Parameter 'URL' is required by @Test on method Demo but has not been marked @Optional or defined
in C:\Users\Admin\AppData\Local\Temp\testng-eclipse--2004867649\testng-customsuite.xml]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Parameter 'URL' is required by @Test on method Demo but has not been marked @Optional or defined
in C:\Users\Admin\AppData\Local\Temp\testng-eclipse--2004867649\testng-customsuite.xml
	at org.testng.internal.Parameters.createParameters(Parameters.java:154)
	at org.testng.internal.Parameters.createParameters(Parameters.java:361)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:451)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Demo -->
        <test-method signature="TimeOut()[pri:0, instance:Frameworks.TestNG1@5f354bcf]" started-at="2024-01-07T15:28:52Z" name="TimeOut" finished-at="2024-01-07T15:28:52Z" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TimeOut -->
        <test-method signature="A()[pri:0, instance:Frameworks.TestNG1@5f354bcf]" started-at="2024-01-07T15:28:52Z" name="A" finished-at="2024-01-07T15:28:52Z" depends-on-methods="Frameworks.TestNG1.B, Frameworks.TestNG1.Demo" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNG1.A()[pri:0, instance:Frameworks.TestNG1@5f354bcf] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNG1.A()[pri:0, instance:Frameworks.TestNG1@5f354bcf] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- A -->
      </class> <!-- Frameworks.TestNG1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
